### ISSUE TITLE
Implement Command-Line interface

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#19]
We need to implement command-line interface for automation purpose. The list of commands to implement:
- list
- install
- install-package
- uninstall
- start
- stop
- kill

**Comment by AlenPelin** [comment]
Postponed or cancelled for 1.4

**Comment by AlenPelin** [comment]
Implement following commands/options:

1. sim tools-validate-machine
2. sim download --name "Sitecore CMS" --version 8.1 --revision 151207
3. sim download --name "Web Forms for Marketers" --version 8.1 --revision 151207
4. sim tools-generate-nugets
5. sim install --name "habitat.local" --hosts "habitat.local|site.habitat.local" ...
6. sim restore --name "habitat.local" --mongo "http://localhost:27017/sitecore_analytics"  --file "C:\backups\analytycs.bak"

Validate and fix if doesn't work:

1. sim installmodule --module "Web Forms for Marketers"

**Comment by sergeyshushlyapin** [comment]
Hi there,

Wondering if this issue is still open and actual... I would like to [use SIM in my build scripts](https://sitecore.stackexchange.com/questions/6052/can-i-use-sim-command-line-for-local-deployments) to install/remove Sitecore instances. I can tell you that SIM is mentioned and _recommended_ by the new [Sitecore eLearning](http://www.sitecore.net/en/company/press-and-media/press-releases/2017/02/elearning-announcement-for-8-2) site as a tool for continuous deployment. They expect the tool to be found by the following path:

```
set sim="%appdata%\Sitecore\Sitecore Instance manager\Apps\SIMCMD\sim.exe"
```

The problem is that I didn't managed to find the `sim.exe` neither using the path above nor searching through the entire `C:\` drive.. Am I missing something? Thanks!

**Comment by AlenPelin** [comment]
@sergeyshushlyapin they are wrong, you should always use SIM -> Ribbon -> Bundled Tools -> Command Line to get latest version of the utility.

**Comment by sergeyshushlyapin** [comment]
That's awesome, thanks a lot!
I didn't know it needs to be downloaded independently! That is the first menu in the Bundled Tools but _I have never seen it_! My vote is for delivering it OOTB ;)

BWT, when installing an instance via SIM UI, the _default_ host name consists of the the site name + `.local` prefix:
![image](https://user-images.githubusercontent.com/4719165/26962590-df06deb6-4cef-11e7-9b57-03dc90f512c3.png)

But that is not the case when installing the instance via command line. In this case the host equals to the instance name. That is a minor thing, but it would be great to keep this behavior in sync. Please let me know if I should register a new issue for that.

**Comment by AlenPelin** [comment]
@sergeyshushlyapin it is not a bug :), SIMCMD != SIM and the behaviour may be different.

**Comment by BIGANDYT** [comment]
Is there a publish site option? Using SIMCMD to install a sitecore 8 instance and looking for options to publish the site after ive installed the instance and deployed my items using unicorn.

**Comment by AlenPelin** [comment]
SIMCMD is discontinued as SIF covers its main task. I propose to try to execute Sitecore PowerShell Extensions via PS remoting instead.
