### ISSUE TITLE
Hide/Disable buttons not available for Sitecore 9 environments

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#249]
When selecting Sitecore 9 instance/environment the features/buttons that are not yet implemented for this Sitecore version should be hidden/disabled so that we do not get any errors/exceptions when something unexpected is clicked.

**Comment by IvanSheyenko** [comment]
backup, restore, export, install modules are available for 9. Do they really work?

**Comment by DmitryKolinchuk** [comment]
@IvanSheyenko, it's needed to be checked.

**Comment by DmitryKolinchuk** [comment]
@RomanChernyk @IvanSheyenko @AndreyFilchenkov I tested these commands using the CM instance of Sitecore 9.0.1 XM1.
The Backup command makes the backup correctly in the root folder where all Sitecore instances are located.
However, the Export and Restore commands don't work properly due to incorrect resolving of paths to needed folders in the code.
The Install Packages command also fails on Starting the instance action.

I would suggest hiding theses commands for Sitecore 9 in scope of this task for now.
Then we can ask engineers if these commands are really needed because in my opinion they are rarely used.
What do you think?

**Comment by DmitryKolinchuk** [comment]
The following commands should be hidden for all Sitecore 9 instances:
- Install Packages
- Backup
- Restore

The following commands should be hidden for Sitecore 9 sites that don't have Sitecore.Kernel (e.g. XConnect):
- Sitecore Client
- Log in admin
- Config Files
- Log Files
- Visual Studio

The context menu should be updated as follows:
![HideUI](https://user-images.githubusercontent.com/20965100/67844852-24aa6380-fb07-11e9-829d-cbc411d9b5ba.png)

**Comment by AndreyFilchenkov** [comment]
The issue was implemented. 
PR: https://github.com/Sitecore/Sitecore-Instance-Manager/pull/292
