### ISSUE TITLE
Get sitecore and version 9

### ISSUE THREAD

**Issue by IvanSheyenko** [Sitecore/Sitecore-Instance-Manager#341]
Download sitecore feature downloads sitecore web root archive for "classic" SIM installation. This should be modified to download SIF package.

**Comment by AndreyFilchenkov** [comment]
To complete this task, we need to update the SIS database. So it is postponed until the SIS build/rebuild is fixed.

**Comment by DmitryKolinchuk** [comment]
The 'Info Service - Update Local Folder' build task fails due to the following error:
`System.InvalidOperationException: Failed to build configuration. Reason: Could not load file or assembly 'Microsoft.Practices.EnterpriseLibrary.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.`
The build server does not contain needed version of the 'Microsoft.Practices.EnterpriseLibrary.Common.dll' assembly in GAC.
