### ISSUE TITLE
Instance.GetDataFolderPath() fails for SC10.0

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#501]
Steps to reproduce:
1. Install Sitecore 10.0;
2. Select any environment member(e.g. cm, cd, id);
3. The following error occurs:

```
   8 09:29:51,914 INFO  Issue with reading ModulesNames propery of CLI-sc100r004346XP0Id.local instance.
System.InvalidOperationException: Cannot get data folder of C:\inetpub\wwwroot\CLI-sc100r004346XP0\CLI-sc100r004346XP0Id.local
   at SIM.Instances.Instance.GetDataFolderPath()
   at SIM.Instances.Instance.get_PackagesFolderPath()
   at SIM.Instances.Instance.get_ModulesFiles()
   at SIM.Instances.Instance.get_Modules()
   at SIM.Instances.Instance.get_ModulesNames()

```

**Comment by DmitryKolinchuk** [comment]
The issue occurs due to using the 'SIM.Instances.PartiallyCachedInstance.ModulesNames' property for Sitecore 9+ instances.
It is used to display modules that are located in the 'packages' folder of an instance:
![image](https://user-images.githubusercontent.com/20965100/114723169-1f64c700-9d43-11eb-9b28-7da14d2f027e.png)
Looks like this functionality should be deprecated for all Sitecore versions.
