### ISSUE TITLE
Give meaningful names in "Revision" dropdown in "Installing new instance" window

### ISSUE THREAD

**Issue by sc-AndriyShcherbak** [Sitecore/Sitecore-Instance-Manager#652]
![image](https://user-images.githubusercontent.com/52037942/148513657-ff7c355d-caa5-48da-8dc7-45a7afa861a6.png)

For example for Sitecore 10.1, it's hard to identify what Sitecore version is about to be installed. I have tried to rename the packages but it led to issues with installing.

It would be great to display some meaningful names in this dropdown to be able to see what version will be installed. For example, Sitecore 10.1.1, Sitecore 10.1.2, etc.

**Comment by DmitryKolinchuk** [comment]
For Sitecore 9.3 and lower, the information about update is available as demonstrated in the following screenshot:
![image](https://user-images.githubusercontent.com/20965100/217780671-c0cb1dc4-9d78-4ac2-8d95-fda8449481ad.png)

For newer Sitecore versions it is not available since there is no data in [Sitecore-Information-Service](https://dev.azure.com/Sitecore-PSS/Sitecore%20Information%20Service/_git/Sitecore-Information-Service?path=/data/Products/Sitecore%20CMS) about these versions.

**Comment by DmitryKolinchuk** [comment]
Data in [Sitecore-Information-Service](https://dev.azure.com/Sitecore-PSS/Sitecore%20Information%20Service/_git/Sitecore-Information-Service?path=/data/Products/Sitecore%20CMS) was updated, final configuration and json files were built by the 'Info Service - Update Local Folder' task and moved to [https://dl.sitecore.net/updater/info/v4](https://dl.sitecore.net/updater/info/v4), so information about actual Sitecore versions is available now.
