### ISSUE TITLE
Add ability to add the Sitecore modules to the Dockerized environment

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#653]
Add ability to add the Sitecore modules to the Dockerized environment.

E.g. we can add the SPE, SXA modules to the containerized environment deployed by SIM.

It can be done by using proper "docker-compose.*.yaml" patch files.

**Comment by DmitryKolinchuk** [comment]
The following examples can be used as a base for implementation because they already contain SPE, SXA and Horizon modules:
[https://github.com/Sitecore/docker-examples/tags](https://github.com/Sitecore/docker-examples/tags)

**Comment by DmitryKolinchuk** [comment]
Since the task is quite complicated and requires specific implementation for each module, it was decided to implement support only of SPE and SXA modules in scope of this task.
Adding support of Horizon, Publishing Service and JSS modules has been registered in the following separate issues:
[https://github.com/Sitecore/Sitecore-Instance-Manager/issues/663](https://github.com/Sitecore/Sitecore-Instance-Manager/issues/663)
[https://github.com/Sitecore/Sitecore-Instance-Manager/issues/664](https://github.com/Sitecore/Sitecore-Instance-Manager/issues/664)
[https://github.com/Sitecore/Sitecore-Instance-Manager/issues/665](https://github.com/Sitecore/Sitecore-Instance-Manager/issues/665)
Other potential modules are:
[Sitecore Content Hub Connector](https://github.com/Sitecore/container-deployment/releases/tag/chub%2F5.0.0.00328.598)
[Sitecore Experience Edge Connector](https://github.com/Sitecore/container-deployment/releases/tag/expedge%2F18.0.0.00105.87)
