### ISSUE TITLE
Question. Plugins support in next releases

### ISSUE THREAD

**Issue by stasmaxymov** [Sitecore/Sitecore-Instance-Manager#68]
Develop branch has changes that remove plugins support from SIM. Could you share information will be any replacement for plugins functionality in coming releases

**Comment by AlenPelin** [comment]
There will not be any plugin replacement functionality as this feature wasn't used much and only added unnecessary complexity. Instead of plugins I suggest to maintain a fork of SIM with desired functionality as it is easier for end-user to use custom version of SIM rather than installing plug-ins, or create pull request to get this extra functions in the main version of SIM.
