### ISSUE TITLE
Using graphical setup package by SIM

### ISSUE THREAD

**Issue by YevhenPetlovanyi** [Sitecore/Sitecore-Instance-Manager#774]
Description or scenario: 
SIM can use graphical setup packages to install Sitecore. The advantage of this approach is the ability to install the SXA module at the same time as installing Sitecore:
![SIM](https://github.com/Sitecore/Sitecore-Instance-Manager/assets/91549330/904e9b18-81ee-4936-9c00-db9ebbb2b242)

![image](https://github.com/Sitecore/Sitecore-Instance-Manager/assets/91549330/a3d6f6cb-8818-446f-9b3b-d354a5d51814)

Valid for version:тSitecore 10.3.0 and earlier

Could you test this approach and indicate if it is supported?

I hereby confirm the issue is new:
* all SIM [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#known-issues) or [existing issue](https://github.com/Sitecore/Sitecore-Instance-Manager/issues)

**Comment by DmitryKolinchuk** [comment]
I tested the installation, reinstallation and deletion using [Sitecore 10.3.1 rev. 009452 (Setup XP0 Developer Workstation rev. 1.5.1-r2).zip](https://sitecoredev.azureedge.net/~/media/77797548A634453585360E7FF67B012D.ashx?date=20230801T111126) and it works well.
However, it was discussed with @ValeriyLeman that we cannot support this approach officially, because SIM was not initially designed to work with graphical setup packages, so testing and maintaining the related functionality is not in scope.
Anyway, this approach is a very good finding and should be shared with other users to be used depending on their needs.
