### ISSUE TITLE
Modules installation via SIF templates support

### ISSUE THREAD

**Issue by AndreyKomarov** [Sitecore/Sitecore-Instance-Manager#783]
**Description or scenario:**  
I have noticed that a few modules have SIF installation files.
Example:
[SXA](https://dev.sitecore.net/Downloads/Sitecore_Experience_Accelerator/9x/Sitecore_Experience_Accelerator_930.aspx#:~:text=Package%20of%20SIF%20templates%20files)
[Sitecore AI Automated Personalization](https://dev.sitecore.net/Downloads/Sitecore_AI_Automated_Personalization_Standard/4x/Sitecore_AI_Automated_Personalization_Standard_400.aspx#:~:text=The%20zip%20package%20containing%20SIF%20template%20files)
[DEF Tenant Service](https://dev.sitecore.net/Downloads/Data_Exchange_Framework/2x/Data_Exchange_Framework_210.aspx#:~:text=Provides%20an%20ability%20to%20install%20Tenant%20Service%20using%20Sitecore%20Installation%20Framework)

It would be nice if we could support this OOTB.

**Valid for version:**  
It should be valid for 9.3+. However, it depends on the module.

**Issue is actual:**  
I hereby confirm the issue is new:
* all SIM [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#known-issues) or [existing issue](https://github.com/Sitecore/Sitecore-Instance-Manager/issues)

**Comment by DmitryKolinchuk** [comment]
Out of the box SIM contains the following configuration files that allow to install Sitecore 9+ XP0 with SXA:
_\src\SIM.Tool\GlobalParamsConfig\XP\GlobalParams_9.3_XP0_SXA.json
\src\SIM.Tool\GlobalParamsConfig\XP\GlobalParams_10.0_XP0_SXA.json_
This can be done using the Installation graphical setup package (e.g. [Sitecore 10.3.0 rev. 008463 (Setup XP0 Developer Workstation rev. 1.5.0-r11).zip](https://scdp.blob.core.windows.net/downloads/Sitecore%20Experience%20Platform/103/Sitecore%20Experience%20Platform%20103/Secure/WDP/Sitecore%2010.3.0%20rev.%20008463%20(Setup%20XP0%20Developer%20Workstation%20rev.%201.5.0-r11).zip)) as described in the issue [https://github.com/Sitecore/Sitecore-Instance-Manager/issues/774](https://github.com/Sitecore/Sitecore-Instance-Manager/issues/774).
I checked that this approach does not work, for example, with the [Sitecore 10.3.0 rev. 008463 (Setup XM1 Developer Workstation rev. 1.5.0-r11).zip](https://scdp.blob.core.windows.net/downloads/Sitecore%20Experience%20Platform/103/Sitecore%20Experience%20Platform%20103/Secure/WDP/Sitecore%2010.3.0%20rev.%20008463%20(Setup%20XM1%20Developer%20Workstation%20rev.%201.5.0-r11).zip) package because there is no configuration (.json) that allows to install SXA in the XM1 topology using SIF templates.

I also performed the following test after fixing the issue [https://github.com/Sitecore/Sitecore-Instance-Manager/issues/785](https://github.com/Sitecore/Sitecore-Instance-Manager/issues/785):
1. Download the [SXA SIF Templates 10.4.0 rev. 08675.zip](https://scdp.blob.core.windows.net/downloads/Sitecore%20Experience%20Accelerator/10x/Sitecore%20Experience%20Accelerator%201040/SXA%20SIF%20Templates%2010.4.0%20rev.%2008675.zip) archive.
2. Copy the following files from it to the Sitecore 10.4.0 rev. 010422 (WDP XM1 packages) folder that was created (unpacked) in the SIM local repository while first installation of SC 10.4.0 XM1:
_spe.json
SXA-SingleDeveloper-XM1.json
sxa-solr.json
sxa-XM1-CD.json
sxa-XM1-CM.json_
3. Download the [Sitecore Experience Accelerator XM 10.4.0 rev. 08675.scwdp.zip](https://scdp.blob.core.windows.net/downloads/Sitecore%20Experience%20Accelerator/10x/Sitecore%20Experience%20Accelerator%201040/Sitecore%20Experience%20Accelerator%20XM%2010.4.0%20rev.%2008675.scwdp.zip) and [Sitecore Experience Accelerator XM 10.4.0 rev. 08675 CD.scwdp.zip](https://scdp.blob.core.windows.net/downloads/Sitecore%20Experience%20Accelerator/10x/Sitecore%20Experience%20Accelerator%201040/Sitecore%20Experience%20Accelerator%20XM%2010.4.0%20rev.%2008675%20CD.scwdp.zip) packages and add them to the same Sitecore 10.4.0 rev. 010422 (WDP XM1 packages) folder.
4. Install SC 10.4.0 XM1 via SIM.

**Result:** the SXA module is not installed.

Based on this, adding support of SIF templates requires creating the configuration (.json) related to each module which is quite time-expansive and hard to manage task.
Most of modules can installed via regular package, so [the Install Packages button](https://github.com/Sitecore/Sitecore-Instance-Manager/issues/557) in SIM can be used for this purpose.

**Comment by DmitryKolinchuk** [comment]
Discussed with @AndreyKomarov that it would be great to add at least native support of SXA installation using SIF templates.
